language: c++
sudo: required
notifications:
  email:
    recipients:
      - dagmcci@googlegroups.com
  slack: cnerg:d48My26ZXfvHlg0On2WwNQFi
env:
  matrix:
    # astyle only
    - ASTYLE_ONLY="ON"
    # main
#   - ASTYLE_ONLY="OFF" COMPILER="gcc-7"     MOAB_VERSION="5.1"    BUILD_GEANT4="ON"
#   - ASTYLE_ONLY="OFF" COMPILER="clang-5.0" MOAB_VERSION="5.1"    BUILD_GEANT4="ON"
    # vary moab version
    - ASTYLE_ONLY="OFF" COMPILER="gcc-7"     MOAB_VERSION="master" BUILD_GEANT4="ON"
    - ASTYLE_ONLY="OFF" COMPILER="clang-5.0" MOAB_VERSION="master" BUILD_GEANT4="ON"
    # vary compiler
#   - ASTYLE_ONLY="OFF" COMPILER="gcc-4.8"   MOAB_VERSION="5.1"    BUILD_GEANT4="OFF"
#   - ASTYLE_ONLY="OFF" COMPILER="gcc-5"     MOAB_VERSION="5.1"    BUILD_GEANT4="OFF"
#   - ASTYLE_ONLY="OFF" COMPILER="gcc-6"     MOAB_VERSION="5.1"    BUILD_GEANT4="OFF"
#   - ASTYLE_ONLY="OFF" COMPILER="clang-4.0" MOAB_VERSION="5.1"    BUILD_GEANT4="OFF"
services:
  - docker
before_install:
  - sudo docker pull cnerg/dagmc-ci-ubuntu-16.04
  # get a container id
  - sudo docker run cnerg/dagmc-ci-ubuntu-16.04 /bin/bash -c "cd /root"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  # make the build directory
  - sudo docker run cnerg/dagmc-ci-ubuntu-16.04 /bin/bash -c "mkdir -p /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id cnerg/dagmc-ci-ubuntu-16.04
  # copy the repo in the docker instance
  - sudo docker cp ../DAGMC $commit_id:/root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id cnerg/dagmc-ci-ubuntu-16.04
install:
  - sudo docker run cnerg/dagmc-ci-ubuntu-16.04 /bin/bash -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                                    bash docker/travis.install.sh $ASTYLE_ONLY $COMPILER $MOAB_VERSION $BUILD_GEANT4"
  - commit_id=$(sudo docker ps -l | tail -n1 | awk '{print $1}')
  - sudo docker commit $commit_id cnerg/dagmc-ci-ubuntu-16.04
script:
  - sudo docker run cnerg/dagmc-ci-ubuntu-16.04 /bin/bash -c "cd /root/build/$COMPILER/DAGMC-moab-$MOAB_VERSION/DAGMC;
                                                                    bash docker/travis.script.sh $ASTYLE_ONLY $COMPILER $MOAB_VERSION $BUILD_GEANT4"
